In [4]:
import numpy as np

In [9]:
# Array in numpy
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6] , [7, 8, 9]])

In [6]:
print(a)

[1 2 3]


In [10]:
# Get dimension 
a.ndim
b.ndim

2

In [11]:
# Get the Shape (row and col in their)
a.shape
b.shape

(2, 3)

In [13]:
# Get Type (The int that allocated) and Size(the byte that allocated)
print(a.dtype)
print(a.itemsize)

int32
4


In [15]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get the specific element [row , col]
print(c[1 , 5]) #or we can have (c[1, -2])
print(c[1][5]) # this is another way

13
13


In [20]:
# Get the specific row (or col)
print(c[0, :]) # for col is inverse c[:, 0]
print(c[0])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [29]:
# Get a fantecy c[startindex:endindex:stepsize]
c[0, 1:6:2] #c[0, 1:-1:2]

array([2, 4, 6])

In [33]:
# n dim get element (work outside in)
b =np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)
print(b[0, 1, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
