In [4]:
import numpy as np

In [9]:
# Array in numpy
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6] , [7, 8, 9]])

In [6]:
print(a)

[1 2 3]


In [10]:
# Get dimension 
a.ndim
b.ndim

2

In [11]:
# Get the Shape (row and col in their)
a.shape
b.shape

(2, 3)

In [13]:
# Get Type (The int that allocated) and Size(the byte that allocated)
print(a.dtype)
print(a.itemsize)

int32
4


In [15]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get the specific element [row , col]
print(c[1 , 5]) #or we can have (c[1, -2])
print(c[1][5]) # this is another way

13
13


In [20]:
# Get the specific row (or col)
print(c[0, :]) # for col is inverse c[:, 0]
print(c[0])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [29]:
# Get a fantecy c[startindex:endindex:stepsize]
c[0, 1:6:2] #c[0, 1:-1:2]

array([2, 4, 6])

In [33]:
# n dim get element (work outside in)
b =np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)
print(b[0, 1, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [34]:
# all zeros matrix c(row, col)
d = np.zeros((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
# all ones matrix 
e = np.ones((2, 3, 2))
print(e)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [36]:
# any other number full((shape), value)
f = np.full((1, 2), 5)
print(f)

[[5 5]]


In [37]:
# the look like array make new array 
g = np.full_like(a, 7) # or we can np.full(a.shape, 7)
print(g)

[7 7 7]


In [46]:
# the random decimal array make np.random.rand(shape)
h = np.random.rand(4,2)
print(h)

# random int np.random.randint( 0(or a number ,) to this number, size=(shape))
i = np.random.randint(5, size=(4,2))
print(i)

[[0.77330382 0.5021246 ]
 [0.2002789  0.65432713]
 [0.632636   0.34761515]
 [0.5205834  0.10345776]]
[[2 4]
 [3 4]
 [4 3]
 [0 1]]


In [51]:
# the identity matrix
j = np.identity(5)
print(j)

# repeat the array 
arr = np.array([[1, 2]])
k = np.repeat(arr, 5 , axis=0)
print(k)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]


In [53]:
# the Q for a make array like [[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 9, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]
output = np.ones((5, 5))

z = np.zeros((3, 3))
z[1, 1] = 9 
output[1:-1, 1:-1] = z


print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### be careful  when copy a array!!!

In [54]:
l = np.array([1, 2, 3])
m = l.copy() # if we use m = 1 this two point to the one memory
m[0] = 27
print(l) # if we have m = l here we have [27, 2, 3] 
print(m)

[1 2 3]
[27  2  3]


# mathmatic 

In [56]:
# mathmatic :)
n = np.array([1, 2, 3, 4, 5])

In [65]:
# we have all operations on all elements  
n + 2 # all elements + 2
n - 2
n * 2
n / 2
n ** 2
np.sin(n) # take the sin of value

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

o = np.array(n) # in this case should have a same shape
n + o

# Linear Algebra

In [67]:
# the algebra multiplections 
p = np.ones((2, 3))

q = np.full((3, 2), 2)

np.matmul(p,q)

array([[6., 6.],
       [6., 6.]])

In [68]:
# find determinations of array
r = np.identity(3)
np.linalg.det(r)

1.0

### statictic

In [69]:
s = np.array([[1, 2, 3], [4, 5, 6]])

np.min(s)

1

In [71]:
np.max(s) # set the max element
np.sum(s)

21

## Reorganizing Arrays

In [73]:
# reshape the array
t = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

u = t.reshape((8, 1))
print(u)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [75]:
# vertically stacking vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

np.vstack([v1, v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
# horizantal stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### load data from file

In [83]:
# get the array from a txt file 

u = np.genfromtxt("data.txt" , delimiter=",")
print(u)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]]


#### advance indexing and Boolean masking

In [85]:
# the boolean checking :)
u > 5 # and all operation like this

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [97]:
# get the data in matrix upper than specific num
u[u > 15]

# we can index with list 
w = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
w[[1, 6, 7]]

array([2, 7, 8])

In [99]:
np.any(u > 15 , axis = 0) # np.all  check all element of col(if axis = 0)

array([False, False, False,  True,  True,  True])